/**
 * THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
 * Generated from FengShuiCompass theme definitions.
 */

import type { CompassTheme } from './themes';

export const importedCompassThemes: Record<string, CompassTheme> = {
  compass: {
    info: {
      id: 2,
      name: '经典罗盘',
      preview: 'theme-compass-preview.png',
    },
    animation: {
      enable: true,
      duration: 1000,
      delay: 100,
    },
    rotate: 0,
    autoFontSize: false,
    isShowScale: true,
    compassSize: {
      width: 800,
      height: 800,
    },
    latticeFill: [[0, 3, 'red']],
    line: {
      borderColor: '#AAAAAA',
      scaleColor: '#AAAAAA',
      scaleHighlightColor: '#AAAAAA',
    },
    isShowTianxinCross: true,
    scaleStyle: {
      minLineHeight: 10,
      midLineHeight: 25,
      maxLineHeight: 25,
    },
    data: [
      {
        name: '八数',
        startAngle: 60,
        fontSize: 18,
        textColor: 'white',
        vertical: false,
        togetherStyle: 'empty',
        data: ['一', '二', '三', '四', '五', '六', '七', '八'],
      },
      {
        name: ['后先天八卦', '先天八卦', '龙上八煞'],
        startAngle: 66,
        fontSize: 18,
        textColor: ['white', 'red', 'white'],
        vertical: false,
        togetherStyle: 'equally',
        data: [
          ['坎', '☰', '辰'],
          ['艮', '☲', '寅'],
          ['震', '☱', '申'],
          ['巽', '☴', '酉'],
          ['离', '☵', '亥'],
          ['坤', '☶', '卯'],
          ['兑', '☳', '巳'],
          ['乾', '☷', '午'],
        ],
      },
      {
        name: '九星',
        startAngle: 0,
        textColor: 'white',
        data: ['贪', '巨', '禄', '文', '武', '廉', '破', '辅', '弼'],
      },
      {
        name: '二十四山',
        startAngle: 0,
        textColor: 'white',
        data: [
          '子',
          '癸',
          '丑',
          '艮',
          '寅',
          '甲',
          '卯',
          '乙',
          '辰',
          '巽',
          '巳',
          '丙',
          '午',
          '丁',
          '未',
          '坤',
          '申',
          '庚',
          '酉',
          '辛',
          '戌',
          '乾',
          '亥',
          '壬',
        ],
      },
      {
        name: '微盘二十四星',
        startAngle: 0,
        textColor: 'white',
        data: [
          '天辅',
          '天垒',
          '天汉',
          '天厨',
          '天市',
          '天桔',
          '天苑',
          '天衡',
          '天官',
          '天罡',
          '太乙',
          '天屏',
          '太微',
          '天马',
          '南极',
          '天常',
          '天钺',
          '天关',
          '天潢',
          '少微',
          '天乙',
          '天魁',
          '天厩',
          '天皇',
        ],
      },
      {
        name: '透地六十龙',
        startAngle: 0,
        textColor: 'white',
        vertical: true,
        data: [
          '甲子',
          '丙子',
          '戊子',
          '庚子',
          '壬子',
          '乙丑',
          '丁丑',
          '己丑',
          '辛丑',
          '癸丑',
          '甲寅',
          '丙寅',
          '戊寅',
          '庚寅',
          '壬寅',
          '乙卯',
          '丁卯',
          '己卯',
          '辛卯',
          '癸卯',
          '甲辰',
          '丙辰',
          '戊辰',
          '庚辰',
          '壬辰',
          '乙巳',
          '丁巳',
          '己巳',
          '辛巳',
          '癸巳',
          '甲午',
          '丙午',
          '戊午',
          '庚午',
          '壬午',
          '乙未',
          '丁未',
          '己未',
          '辛未',
          '癸未',
          '甲申',
          '丙申',
          '戊申',
          '庚申',
          '壬申',
          '乙酉',
          '丁酉',
          '己酉',
          '辛酉',
          '癸酉',
          '甲戌',
          '丙戌',
          '戊戌',
          '庚戌',
          '壬戌',
          '乙亥',
          '丁亥',
          '己亥',
          '辛亥',
          '癸亥',
        ],
      },
      {
        name: '透地六十龙旺相',
        startAngle: 0,
        textColor: 'white',
        vertical: false,
        data: [
          '三',
          '八',
          '二',
          '一',
          '四',
          '三',
          '六',
          '一',
          '三',
          '九',
          '八',
          '三',
          '三',
          '七',
          '三',
          '四',
          '五',
          '一',
          '三',
          '五',
          '四',
          '七',
          '二',
          '八',
          '四',
          '六',
          '一',
          '七',
          '三',
          '六',
          '五',
          '九',
          '二',
          '四',
          '一',
          '五',
          '三',
          '五',
          '三',
          '三',
          '三',
          '八',
          '五',
          '七',
          '一',
          '八',
          '三',
          '七',
          '七',
          '九',
          '八',
          '五',
          '二',
          '九',
          '五',
          '七',
          '九',
          '四',
          '九',
          '五',
        ],
      },
    ],
  },
  dark: {
    info: {
      id: 3,
      name: '暗夜主题',
      preview: 'theme-dark-preview.png',
    },
    rotate: 0,
    compassSize: {
      width: 800,
      height: 800,
    },
    latticeFill: [],
    line: {
      borderColor: '#00FFFF',
      scaleColor: '#00FFFF',
      scaleHighlightColor: '#FF0000',
    },
    isShowTianxinCross: true,
    scaleStyle: {
      minLineHeight: 10,
      midLineHeight: 25,
      maxLineHeight: 25,
    },
    data: [
      {
        name: '八数',
        startAngle: 0,
        textColor: 'aqua',
        vertical: false,
        togetherStyle: 'empty',
        data: ['一', '二', '三', '四', '五', '六', '七', '八'],
      },
      {
        name: ['后先天八卦', '先天八卦', '龙上八煞'],
        startAngle: 0,
        fontSize: 18,
        textColor: ['aqua', 'red', 'aqua'],
        vertical: false,
        togetherStyle: 'equally',
        data: [
          ['坎', '☰', '辰'],
          ['艮', '☲', '寅'],
          ['震', '☱', '申'],
          ['巽', '☴', '酉'],
          ['离', '☵', '亥'],
          ['坤', '☶', '卯'],
          ['兑', '☳', '巳'],
          ['乾', '☷', '午'],
        ],
      },
      {
        name: '九星',
        startAngle: 0,
        textColor: 'aqua',
        data: ['贪', '巨', '禄', '文', '武', '廉', '破', '辅', '弼'],
      },
      {
        name: '二十四山',
        startAngle: 0,
        textColor: 'aqua',
        data: [
          '子',
          '癸',
          '丑',
          '艮',
          '寅',
          '甲',
          '卯',
          '乙',
          '辰',
          '巽',
          '巳',
          '丙',
          '午',
          '丁',
          '未',
          '坤',
          '申',
          '庚',
          '酉',
          '辛',
          '戌',
          '乾',
          '亥',
          '壬',
        ],
      },
      {
        name: '微盘二十四星',
        startAngle: 0,
        textColor: 'aqua',
        data: [
          '天辅',
          '天垒',
          '天汉',
          '天厨',
          '天市',
          '天桔',
          '天苑',
          '天衡',
          '天官',
          '天罡',
          '太乙',
          '天屏',
          '太微',
          '天马',
          '南极',
          '天常',
          '天钺',
          '天关',
          '天潢',
          '少微',
          '天乙',
          '天魁',
          '天厩',
          '天皇',
        ],
      },
      {
        name: '透地六十龙',
        startAngle: 0,
        textColor: 'aqua',
        vertical: true,
        data: [
          '甲子',
          '丙子',
          '戊子',
          '庚子',
          '壬子',
          '乙丑',
          '丁丑',
          '己丑',
          '辛丑',
          '癸丑',
          '甲寅',
          '丙寅',
          '戊寅',
          '庚寅',
          '壬寅',
          '乙卯',
          '丁卯',
          '己卯',
          '辛卯',
          '癸卯',
          '甲辰',
          '丙辰',
          '戊辰',
          '庚辰',
          '壬辰',
          '乙巳',
          '丁巳',
          '己巳',
          '辛巳',
          '癸巳',
          '甲午',
          '丙午',
          '戊午',
          '庚午',
          '壬午',
          '乙未',
          '丁未',
          '己未',
          '辛未',
          '癸未',
          '甲申',
          '丙申',
          '戊申',
          '庚申',
          '壬申',
          '乙酉',
          '丁酉',
          '己酉',
          '辛酉',
          '癸酉',
          '甲戌',
          '丙戌',
          '戊戌',
          '庚戌',
          '壬戌',
          '乙亥',
          '丁亥',
          '己亥',
          '辛亥',
          '癸亥',
        ],
      },
      {
        name: '透地六十龙旺相',
        startAngle: 0,
        textColor: 'aqua',
        vertical: false,
        data: [
          '三',
          '八',
          '二',
          '一',
          '四',
          '三',
          '六',
          '一',
          '三',
          '九',
          '八',
          '三',
          '三',
          '七',
          '三',
          '四',
          '五',
          '一',
          '三',
          '五',
          '四',
          '七',
          '二',
          '八',
          '四',
          '六',
          '一',
          '七',
          '三',
          '六',
          '五',
          '九',
          '二',
          '四',
          '一',
          '五',
          '三',
          '五',
          '三',
          '三',
          '三',
          '八',
          '五',
          '七',
          '一',
          '八',
          '三',
          '七',
          '七',
          '九',
          '八',
          '五',
          '二',
          '九',
          '五',
          '七',
          '九',
          '四',
          '九',
          '五',
        ],
      },
    ],
  },
  simple_v2: {
    info: {
      id: 6,
      name: '简约V2主题',
      preview: 'theme-polygon-preview.png',
    },
    rotate: 337.5,
    compassSize: {
      width: 800,
      height: 800,
      tianChiRadius: 200,
    },
    latticeFill: [],
    line: {
      borderColor: '#AAAAAA',
      scaleColor: '#AAAAAA',
      scaleHighlightColor: '#AAAAAA',
    },
    isShowTianxinCross: true,
    scaleStyle: {
      minLineHeight: 10,
      midLineHeight: 25,
      maxLineHeight: 25,
    },
    data: [
      {
        name: '方位',
        startAngle: 0,
        fontSize: 32,
        textColor: '#ffff00',
        vertical: false,
        togetherStyle: 'empty',
        data: ['北', '东北', '东', '东南', '南', '西南', '西', '西北'],
      },
      {
        name: '九星',
        startAngle: 0,
        fontSize: 32,
        textColor: 'white',
        shape: 'circle',
        data: ['贪', '巨', '禄', '文', '武', '廉', '破', '辅', '弼'],
      },
    ],
  },
  polygon: {
    info: {
      id: 4,
      name: '多边形主题',
      preview: 'theme-polygon-preview.png',
    },
    rotate: 337.5,
    compassSize: {
      width: 800,
      height: 800,
    },
    latticeFill: [],
    line: {
      borderColor: '#AAAAAA',
      scaleColor: '#AAAAAA',
      scaleHighlightColor: '#AAAAAA',
    },
    isShowTianxinCross: true,
    scaleStyle: {
      minLineHeight: 10,
      midLineHeight: 25,
      maxLineHeight: 25,
    },
    data: [
      {
        name: '--',
        startAngle: 40,
        textColor: 'white',
        vertical: false,
        togetherStyle: 'empty',
        shape: 'polygon',
        data: [
          '小吉',
          '大凶',
          '大吉',
          '最大吉',
          '中吉',
          '最大凶',
          '小凶',
          '中凶',
        ],
      },
      {
        name: '--',
        startAngle: 0,
        textColor: 'white',
        vertical: false,
        togetherStyle: 'empty',
        shape: 'polygon',
        data: ['伏位', '五鬼', '天医', '生气', '延年', '绝命', '祸害', '六杀'],
      },
      {
        name: ['后先天八卦', '先天八卦', '龙上八煞'],
        startAngle: 0,
        fontSize: 18,
        textColor: ['white', 'red', 'white'],
        vertical: false,
        togetherStyle: 'equally',
        shape: 'polygon',
        data: [
          ['坎', '☰', '辰'],
          ['艮', '☲', '寅'],
          ['震', '☱', '申'],
          ['巽', '☴', '酉'],
          ['离', '☵', '亥'],
          ['坤', '☶', '卯'],
          ['兑', '☳', '巳'],
          ['乾', '☷', '午'],
        ],
      },
      {
        name: '方位',
        startAngle: 0,
        fontSize: 32,
        textColor: '#ffff00',
        vertical: false,
        togetherStyle: 'empty',
        data: ['北', '东北', '东', '东南', '南', '西南', '西', '西北'],
      },
      {
        name: '九星',
        startAngle: 0,
        fontSize: 32,
        textColor: 'white',
        shape: 'circle',
        data: ['贪', '巨', '禄', '文', '武', '廉', '破', '辅', '弼'],
      },
    ],
  },
  crice: {
    info: {
      id: 1,
      name: '圆规主题',
      preview: 'theme-crice.png',
    },
    rotate: 337.5,
    animation: {
      enable: false,
    },
    compassSize: {
      width: 800,
      height: 800,
    },
    latticeFill: [[0, 1, 'rgba(255, 166, 0, 0.57)']],
    line: {
      borderColor: '#AAAAAA',
      scaleColor: '#AAAAAA',
      scaleHighlightColor: '#AAAAAA',
    },
    isShowTianxinCross: false,
    scaleStyle: {
      minLineHeight: 10,
      midLineHeight: 25,
      maxLineHeight: 25,
    },
    data: [
      {
        name: '圆规尺刻度',
        startAngle: 0,
        textColor: 'white',
        vertical: false,
        togetherStyle: 'empty',
        data: [
          '0',
          '30',
          '60',
          '90',
          '120',
          '150',
          '180',
          '210',
          '240',
          '270',
          '300',
          '330',
        ],
      },
      {
        name: '方位',
        startAngle: 0,
        fontSize: 32,
        textColor: '#ffff00',
        vertical: false,
        togetherStyle: 'empty',
        data: ['北', '东北', '东', '东南', '南', '西南', '西', '西北'],
      },
      {
        name: '刻度标记',
        startAngle: 0,
        fontSize: 18,
        textColor: '#cccccc',
        vertical: true,
        togetherStyle: 'empty',
        data: [],
      },
    ],
  },
  simple: {
    info: {
      id: 5,
      name: '简约主题',
      preview: 'theme-polygon-preview.png',
    },
    rotate: 337.5,
    compassSize: {
      width: 800,
      height: 800,
      tianChiRadius: 200,
    },
    latticeFill: [],
    scaleStyle: {
      minLineHeight: 10,
      midLineHeight: 25,
      maxLineHeight: 25,
    },
    line: {
      borderColor: '#AAAAAA',
      scaleColor: '#AAAAAA',
      scaleHighlightColor: '#AAAAAA',
    },
    isShowTianxinCross: true,
    data: [
      {
        name: '方位',
        startAngle: 0,
        fontSize: 32,
        textColor: '#ffff00',
        vertical: false,
        togetherStyle: 'empty',
        data: ['北', '东北', '东', '东南', '南', '西南', '西', '西北'],
      },
      {
        name: '九星',
        startAngle: 0,
        fontSize: 32,
        textColor: 'white',
        shape: 'circle',
        data: ['贪', '巨', '禄', '文', '武', '廉', '破', '辅', '弼'],
      },
    ],
  },
};
export const importedThemeKeys = [
  'compass',
  'dark',
  'simple',
  'polygon',
  'crice',
  'simple_v2',
] as const;

export default importedCompassThemes;
